name: spinqick
dependencies:
    - lmfit
    - matplotlib
    - netcdf4
    - numpy<2.0
    - pydantic
    - python>=3.10
    - scipy
    - Pyro4
    - scikit-learn

    # Addtional dev dependencies
    - black
    - docformatter
    - ipython
    - isort
    - mypy
    - pre-commit
    - pre-commit-hooks
    - pylint
    - pytest
    - ruff
